export const productsData = [
  {
    id: 1,
    product_name: "Smart Watch Amazfit Bip 3 Black",
    product_image: "product1",
    product_price: 625_000,
    dicount_price: 564_000,
    reviews: 2,
    discount: true,
  },
  {
    id: 2,
    product_name: "Smart Watch Amazfit Bip 3 Black",
    product_image: "product1",
    product_price: 625_000,
    dicount_price: 564_000,
    reviews: 2,
    discount: false,
  },
  {
    id: 3,
    product_name: "Smart Watch Amazfit Bip 3 Black",
    product_image: "product1",
    product_price: 625_000,
    dicount_price: 564_000,
    reviews: 2,
    discount: true,
  },
  {
    id: 4,
    product_name: "Smart Watch Amazfit Bip 3 Black",
    product_image: "product1",
    product_price: 625_000,
    dicount_price: 564_000,
    reviews: 5,
    discount: false,
  },
  {
    id: 5,
    product_name: "Smart Watch Amazfit Bip 3 Black",
    product_image: "product1",
    product_price: 625_000,
    dicount_price: 564_000,
    reviews: 2,
    discount: true,
  },
  {
    id: 6,
    product_name: "Smart Watch Amazfit Bip 3 Black",
    product_image: "product1",
    product_price: 625_000,
    dicount_price: 564_000,
    reviews: 2,
    discount: false,
  },
  {
    id: 7,
    product_name: "Smart Watch Amazfit Bip 3 Black",
    product_image: "product1",
    product_price: 625_000,
    dicount_price: 564_000,
    reviews: 2,
    discount: true,
  },
  {
    id: 8,
    product_name: "Smart Watch Amazfit Bip 3 Black",
    product_image: "product1",
    product_price: 625_000,
    dicount_price: 564_000,
    reviews: 5,
    discount: false,
  },
];

export const sideBarData = [
  [
    {
      id: 1,
      name: "Super discount for ...",
      img: "discount2",
      desc: "Asaxiy Books",
    },
    {
      id: 2,
      name: "Super discount for ...",
      img: "discount2",
      desc: "Asaxiy Books",
    },
    {
      id: 3,
      name: "Super discount for ...",
      img: "discount2",
      desc: "Asaxiy Books",
    },
    {
      id: 4,
      name: "Super discount for ...",
      img: "discount2",
      desc: "Asaxiy Books",
    },
    {
      id: 5,
      name: "Super discount for ...",
      img: "discount2",
      desc: "Asaxiy Books",
    },
  ],
  [
    {
      id: 7,
      product_name: "Smart Watch Amazfit Bip 3 Black",
      product_image: "product1",
      product_price: 625_000,
      dicount_price: 564_000,
      reviews: 2,
      discount: true,
    },
    {
      id: 8,
      product_name: "Smart Watch Amazfit Bip 3 Black",
      product_image: "product1",
      product_price: 625_000,
      dicount_price: 564_000,
      reviews: 5,
      discount: false,
    },
  ],
];
